os: linux
dist: bionic

language: cpp
python: "3.8"

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgl1-mesa-dev
  
install:
# TODO: Add clang-tidy installation
  - pip install conan --user
  - cd tmxlite && mkdir build && cd build
  - cmake .. 
  - sudo make install 
  - cd ${TRAVIS_BUILD_DIR}
script:

  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . 
  - cat compile_commands.json


after_failure:
  - cd build
  - cat compile_commands.json

