os: linux
dist: bionic

language: cpp
python: "3.8"

compiler:
  - gcc

install:
  pip install conan --user

script:
  - mkdir build
  - cd build
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan install ..
  - cmake ..
  - cmake --build . 




