os: linux
dist: bionic

language: cpp
python: "3.8"

compiler:
  - gcc

before_install:
  sudo apt-get update
  sudo apt-get -y install libgl1-mesa-dev
  
install:
  pip install conan --user

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . 




